2022-11-17 19:35:43,254 INFO    MainThread:4264 [wandb_setup.py:_flush():69] setting env: {}
2022-11-17 19:35:43,254 INFO    MainThread:4264 [wandb_setup.py:_flush():69] setting login settings: {}
2022-11-17 19:35:43,254 INFO    MainThread:4264 [wandb_init.py:_log_setup():337] Logging user logs to D:\projects\python\CenterSnap\external\shape_pretraining\wandb\run-20221117_193543-3jau9oq6\logs\debug.log
2022-11-17 19:35:43,254 INFO    MainThread:4264 [wandb_init.py:_log_setup():338] Logging internal logs to D:\projects\python\CenterSnap\external\shape_pretraining\wandb\run-20221117_193543-3jau9oq6\logs\debug-internal.log
2022-11-17 19:35:43,255 INFO    MainThread:4264 [wandb_init.py:init():370] calling init triggers
2022-11-17 19:35:43,255 INFO    MainThread:4264 [wandb_init.py:init():375] wandb.init called with sweep_config: {}
config: {}
2022-11-17 19:35:43,255 INFO    MainThread:4264 [wandb_init.py:init():419] starting backend
2022-11-17 19:35:43,255 INFO    MainThread:4264 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2022-11-17 19:35:43,263 INFO    MainThread:4264 [backend.py:ensure_launched():135] starting backend process...
2022-11-17 19:35:43,294 ERROR   MainThread:4264 [wandb_init.py:init():787] error
Traceback (most recent call last):
  File "D:\projects\python\work\CenterSnap\env\lib\site-packages\wandb\sdk\wandb_init.py", line 761, in init
    run = wi.init()
  File "D:\projects\python\work\CenterSnap\env\lib\site-packages\wandb\sdk\wandb_init.py", line 422, in init
    backend.ensure_launched()
  File "D:\projects\python\work\CenterSnap\env\lib\site-packages\wandb\sdk\backend\backend.py", line 137, in ensure_launched
    self.wandb_process.start()
  File "D:\projects\python\work\CenterSnap\env\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\projects\python\work\CenterSnap\env\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\projects\python\work\CenterSnap\env\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\projects\python\work\CenterSnap\env\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "D:\projects\python\work\CenterSnap\env\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
